### ISSUE TITLE
Cannot install preview 0.2, Mozilla reports file as corrupt

### ISSUE THREAD

**Issue by Deerath** [Cicero-Interactive/Classic-YouTube-Design#5]
I will preface this by saying that I'm new to manually installing addons to firefox.

I went to addons, clicked the "manage addons" cog, clicked "Install add-on from file" then selected the preview .zip that I downloaded.

Mozilla reported that "the add-on downloaded from this site could not be installed because it appears corrupt"

I assume it is me doing something wrong. Does it need to be an .xpi or something, or am I just completely dumb?

Thanks.

**Comment by NebelNidas** [comment]
Downloading the addon normally through [AMO](https://addons.mozilla.org/de/firefox/addon/classic-youtube-design/) should work fine:
![2020-09-30-07-27-04](https://user-images.githubusercontent.com/48808497/94646452-8dd5c080-02ee-11eb-9153-d4d59936cb6f.gif)

As for installing the addon manually (why would you want to do that?), where did you get your .zip file from? As far as I know AMO doesn't provide zips, only the converted xpis... 🤔

**Comment by Deerath** [comment]
The zip file came from here on github. 

Here is the version I have installed now:
Version 0.1.1
Last Updated March 1, 2020

I'm guessing I need to totally remove the old version and install the new one? I'll do that, but like I said I'm a bit dim when it comes to not having automatically updating addons, so my apologies there.

**Comment by NebelNidas** [comment]
Ah, now I understand, so you tried downloading it through this button:
![image](https://user-images.githubusercontent.com/48808497/94647865-ae534a00-02f1-11eb-974d-2613a9fd6797.png)

This will not work, because Mozilla only allows signed extensions in Firefox. In other words, you have to download them from the [Firefox Addon Store](https://addons.mozilla.org/de/firefox/addon/classic-youtube-design/). 😉

**Comment by Deerath** [comment]
That did it, thanks very much! Sorry for being a pain about it.

**Comment by NebelNidas** [comment]
No problem, I should have probably made that more clear in the Readme. Also, small tip: If you want to install an addon manually which isn't on the Firefox addon store, you just have to go to `about:debugging`, select `This Firefox` on the left hand side and then click on the `Load temporary addon` button, from where you can select the downloaded .zip. Note that the addon will only be loaded for one session, though, so you would have to do this every time you restart Firefox!
